server: 
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3301/springsecurity
    username: root
    password: 08112001
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibenate:
        dialect:org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
  expiration: 36000000